# Generated by Django 4.2.9 on 2026-05-09 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2'), ('5-3-2', '5-3-2'), ('3-4-3', '3-4-3'), ('4-1-4-1', '4-1-4-1')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='formations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TacticCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('style', models.CharField(choices=[('Attacking', 'Attacking'), ('Defensive', 'Defensive'), ('Balanced', 'Balanced'), ('Counter', 'Counter')], default='Balanced', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tactic_cards', to='tactics.formation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tactic Card',
                'verbose_name_plural': 'Tactic Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
