# Generated by Django 4.2.9 on 2026-05-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tactics", "0002_tactical_architecture"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="countertactic",
            new_name="tactics_cou_formati_96f832_idx",
            old_name="counter_formation_effectiveness_idx",
        ),
        migrations.RenameIndex(
            model_name="countertactic",
            new_name="tactics_cou_counter_6f9df4_idx",
            old_name="counter_countered_by_idx",
        ),
        migrations.RenameIndex(
            model_name="formation",
            new_name="tactics_for_is_meta_bdf7c8_idx",
            old_name="formation_is_meta_play_style_idx",
        ),
        migrations.RenameIndex(
            model_name="formation",
            new_name="tactics_for_difficu_674b8b_idx",
            old_name="formation_difficulty_level_idx",
        ),
        migrations.RenameIndex(
            model_name="formation",
            new_name="tactics_for_attacki_0dba59_idx",
            old_name="formation_ratings_idx",
        ),
        migrations.RenameIndex(
            model_name="metatracker",
            new_name="tactics_met_popular_70f4c4_idx",
            old_name="meta_popularity_rank_idx",
        ),
        migrations.RenameIndex(
            model_name="metatracker",
            new_name="tactics_met_win_rat_bb382c_idx",
            old_name="meta_win_rate_idx",
        ),
        migrations.RenameIndex(
            model_name="metatracker",
            new_name="tactics_met_usage_c_a20cfb_idx",
            old_name="meta_usage_count_idx",
        ),
        migrations.RenameIndex(
            model_name="playerposition",
            new_name="tactics_pla_formati_3f8d44_idx",
            old_name="position_formation_role_idx",
        ),
        migrations.RenameIndex(
            model_name="playerposition",
            new_name="tactics_pla_display_a45999_idx",
            old_name="position_display_order_idx",
        ),
        migrations.RenameIndex(
            model_name="tacticcard",
            new_name="tactics_tac_formati_63922d_idx",
            old_name="tacticcard_formation_created_idx",
        ),
    ]
